### ISSUE TITLE
Is there any way to tell how large the "plot" will be?

### ISSUE THREAD

**Issue by jeffgreen123** [deepayan/lattice#5]
I just want to know if there is a way to tell how many points the trellis object plot (not x labels and main title, just the plot) will take up? 

Similar to how grobs you can call 

convertUnit(
	grobHeight(legend.grob),
	unitTo = 'inches',
	axisFrom = 'y',
	typeFrom = 'dimension',
	valueOnly = TRUE
	);

Is this possible/can be made possible? 

Thanks,
Jeff

**Comment by pmur002** [comment]
Do you meant something like this ... ?

library(lattice)
xyplot(1, 1)
library(grid)
downViewport("plot_01.panel.1.1.vp")
convertWidth(unit(1, "npc"), "in")
grid.rect(.5, .5, convertWidth(unit(1, "npc"), "in"), unit(1, "lines"), gp=gpar(col="red"))

**Comment by jeffgreen123** [comment]
Yes, that result is what i want, but sadly I want to know if there is a way to figure out what the sixe will be prior to calling xyplot(1,1), like from the trellis object output from x=xyplot(1, 1)

**Comment by pmur002** [comment]
The calculation has to know the size of the device that we are drawing on (otherwise the plot region, which is basically what is left over once everything else has been allocated, is undefined).  You can do this off-screen with an in-memory device like this ...

library(lattice)
library(grid)
pdf(NULL)
xyplot(1 ~ 1)
downViewport("plot_01.panel.1.1.vp")
convertWidth(unit(1, "npc"), "in")

... though the answer is only completely accurate for a PDF device.  Another option would be to use a file-based device like png() or pdf() (with a file specified).

Does that help?
> dev.off()

**Comment by jeffgreen123** [comment]
Yep, that is perfect, i think this will do. Thank you!
